### ISSUE TITLE
timeZoneOffsets does not contain CET

### ISSUE THREAD

**Issue by georgiossalon** [AKushWarrior/instant#3]
In the timezone.dart file, the map entry 'CET' is missing. There is only the 'CEST' to be found.

**Comment by AKushWarrior** [comment]
what offset from UTC is it? I can add it real quick.

**Comment by georgiossalon** [comment]
CET is UTC +1. As a note, CET is only active during a given interval and "replaced" by CEST for the remaining interval

**Comment by AKushWarrior** [comment]
> As a note, CET is only active during a given interval and "replaced" by CEST for the remaining interval

I'll add it at some point. In the meantime, you can probably use dateTimeToOffset and provide the offset as a number of hours.

My current approach to "revolving" time zones is to provide both and allow the developer to pick which they want situationally.

**Comment by AKushWarrior** [comment]
Merged your PR. Updating pub.dev now...

**Comment by AKushWarrior** [comment]
pushed to pub.dev; closing this issue.

Thanks for your contribution.
