### ISSUE TITLE
Not working while converting IST to EST 

### ISSUE THREAD

**Issue by HitendraRathod10** [AKushWarrior/instant#9]
DateTime myDT = DateTime.now();//Current DateTime
    print("current time :- ${myDT}");
//current time :- 2022-03-24 17:44:12.158026

    DateTime EST = dateTimeToZone(zone: "EST", datetime: myDT);//DateTime in EST zone
    print("EST time :- ${EST}");
//EST time :- 2022-03-24 07:14:12.158026Z

this is my code. And right now I check EST zone time on Google it's 8:14 .
Why I m getting difference?

**Comment by AKushWarrior** [comment]
Instant timezones are not daylight-savings aware. Since the east coast is currently using EDT, the provided EST time is one hour behind the daylight savings time.

This is currently expected behavior; i'm working on finding a better system for timezone management.
